### ISSUE TITLE
Alter Market Description on Main Carousal 

### ISSUE THREAD

**Issue by katherineshaw** [Vikamoiseenko/harvestposse#109]
Status-quo: The descriptions on the index page are long, and do not show up well on mobile. 
![image](https://cloud.githubusercontent.com/assets/13126241/9264281/53214c4c-41d9-11e5-80a3-0a7a67d645bd.png)

Long descriptions need to taken down, and months that the market is open need to be put in it's place on carousal. For the image above, instead of that long description, simply "year round" needs to be it's place.

Definition of done: The months that the particular market is open are all that is on the carousal.

**Comment by mrbrianbaker** [comment]
I added the months and day/times open as well, because it looked funny with the name of the market and "year round" under it.
