### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by akneuattenuate** [Vikamoiseenko/harvestposse#16]

**Comment by katherineshaw** [comment]
![image1](https://cloud.githubusercontent.com/assets/13126241/8686643/f4b04f72-2a3c-11e5-98de-aeb218fdd361.jpeg)
![image2](https://cloud.githubusercontent.com/assets/13126241/8686645/f4b1314e-2a3c-11e5-9f5f-ae5797df3a95.jpeg)
![image3](https://cloud.githubusercontent.com/assets/13126241/8686641/f4b01dd6-2a3c-11e5-818d-ea7cb23cf50c.jpeg)
![image4](https://cloud.githubusercontent.com/assets/13126241/8686640/f4af596e-2a3c-11e5-99c9-7a7164d001b3.jpeg)
![image5](https://cloud.githubusercontent.com/assets/13126241/8686644/f4b11f92-2a3c-11e5-9824-c6b4e6d9dbf8.jpeg)
![image6](https://cloud.githubusercontent.com/assets/13126241/8686642/f4b01b1a-2a3c-11e5-9549-15ab2754fc91.jpeg)
![image7](https://cloud.githubusercontent.com/assets/13126241/8686648/f4c9623c-2a3c-11e5-960f-3f0aed3f3b1d.jpeg)
![image8](https://cloud.githubusercontent.com/assets/13126241/8686647/f4c884ca-2a3c-11e5-9551-d765e68bee1c.jpeg)
![image9](https://cloud.githubusercontent.com/assets/13126241/8686649/f4ca54bc-2a3c-11e5-9b00-a91e353b5dab.jpeg)
![image10](https://cloud.githubusercontent.com/assets/13126241/8686646/f4c658c6-2a3c-11e5-9473-e698e63a4197.jpeg)
