### ISSUE TITLE
Implement written content

### ISSUE THREAD

**Issue by akneuattenuate** [Vikamoiseenko/harvestposse#76]
Implement the contents into  "what we do" and  "about page" from https://github.com/Vikamoiseenko/harvestposse/blob/master/writtencontent.docx

Definition of Done: Contents have been implemented into "what we do" and  "about page".

**Comment by Vikamoiseenko** [comment]
add content into index.php and about.php

**Comment by akneuattenuate** [comment]
Hi. Victoria can u plz add the content to our home page.
